singleQuote   = true
trailingComma = "all"
proseWrap     = "always"
printWidth    = 120
endOfLine     = "lf"
tabWidth      = 2
plugins       = ["prettier-plugin-go-template"]

[[overrides]]
files = ["layouts/**/*.html"]
[overrides.options]
parser = "go-template"
